version: 2

# Build configuration
build:
  os: ubuntu-20.04
  tools:
    python: '3.9'
  apt_packages:
    - graphviz
#    - build-essential
#    - gcc-10
#    - g++-10
#    - cpp-10
  commands:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pydl8.5
    - sphinx-build -b html doc _readthedocs/html

sphinx:
  builder: html
  configuration: doc/conf.py
